# NumPy 学习笔记

## 第1章：NumPy基础

### 1.1 NumPy ndarray：一种多维数组对象

In [22]:
# 导入numpy，约定俗成使用np作为别名
import numpy as np

In [23]:
# 生成随机数据
data = np.random.randn(2, 3)
data

array([[ 0.12970242, -0.97538706,  0.39803502],
       [-0.95289766,  0.5547586 , -1.57256136]])

In [24]:
# ndarray与标量运算
data * 10

array([[  1.29702422,  -9.75387061,   3.9803502 ],
       [ -9.52897661,   5.54758603, -15.72561356]])

In [25]:
data + data

array([[ 0.25940484, -1.95077412,  0.79607004],
       [-1.90579532,  1.10951721, -3.14512271]])

In [26]:
# shape属性：各维度大小
data.shape

(2, 3)

In [27]:
# dtype属性：数组的数据类型
data.dtype

dtype('float64')

### 1.2 创建ndarray

In [28]:
# 使用array函数从列表创建数组
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [29]:
# 嵌套序列会创建多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
# ndim属性：数组的维度数
arr2.ndim

2

In [31]:
arr2.shape

(2, 4)

In [32]:
# zeros创建全0数组
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
# 创建多维zeros数组
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
# empty创建空数组（注意：值不一定是0！）
np.empty((2, 3, 2))

array([[[8.65936439e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [8.65774283e-312, 4.08795017e-037]],

       [[1.52789106e+160, 1.43830480e-051],
        [6.03389497e+174, 1.70363122e+160],
        [9.85513222e+165, 8.93704583e+165]]])

In [35]:
# arange是Python range的数组版
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 1.3 ndarray的数据类型

In [36]:
# 创建数组时指定dtype
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [37]:
arr2.dtype

dtype('int32')

In [38]:
# 使用astype转换数据类型
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [39]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [40]:
# 浮点数转整数会截断小数部分
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [41]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [42]:
# 字符串数字转数值
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

### 1.4 NumPy数组的运算

In [43]:
# 数组与数组的运算（逐元素）
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [44]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [45]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
# 数组与标量运算（广播）
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [47]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [48]:
# 数组比较（返回布尔数组）
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [49]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### 1.5 基本的索引和切片

In [50]:
# 一维数组索引
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[5]

np.int64(5)

In [52]:
arr[5:8]

array([5, 6, 7])

In [53]:
# 注意：切片是视图，修改会影响原数组！
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [54]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [55]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [56]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [57]:
# 使用copy方法创建副本
arr_copy = arr[5:8].copy()
arr_copy

array([64, 64, 64])

In [58]:
# 二维数组索引
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [59]:
# 两种等价的索引方式
arr2d[0][2]

np.int64(3)

In [60]:
arr2d[0, 2]

np.int64(3)

In [61]:
# 三维数组索引
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr3d[1, 0]

array([7, 8, 9])

### 1.6 切片索引

In [66]:
# 一维数组切片
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [67]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [68]:
# 二维数组切片
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
# 二维数组双切片
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [71]:
arr2d[1, :2]

array([4, 5])

In [72]:
arr2d[:2, 2]

array([3, 6])

In [73]:
# 只写冒号表示选择整个轴
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [74]:
# 对切片赋值
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 1.7 布尔型索引

In [75]:
# 创建示例数据
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [76]:
data

array([[-0.04618696, -0.01695548,  1.50295203, -0.55685797],
       [-0.69909782,  0.25444505, -0.50931037, -0.32800652],
       [-1.44635553, -0.91756488, -0.92811163, -1.58459522],
       [ 0.84674012,  0.86007893,  0.73897786, -0.63438956],
       [ 0.44650849, -1.75408489,  1.82755766, -0.41309323],
       [ 0.66343348, -1.15096015, -0.67111496, -0.81461321],
       [-0.04686698,  1.20385326,  1.67835257,  2.01095527]])

In [77]:
# 布尔比较
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [78]:
# 使用布尔数组索引
data[names == 'Bob']

array([[-0.04618696, -0.01695548,  1.50295203, -0.55685797],
       [ 0.84674012,  0.86007893,  0.73897786, -0.63438956]])

In [79]:
# 布尔索引与切片结合
data[names == 'Bob', 2:]

array([[ 1.50295203, -0.55685797],
       [ 0.73897786, -0.63438956]])

In [80]:
data[names == 'Bob', 3]

array([-0.55685797, -0.63438956])

In [81]:
# 使用 != 或 ~ 取反
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [82]:
data[~(names == 'Bob')]

array([[-0.69909782,  0.25444505, -0.50931037, -0.32800652],
       [-1.44635553, -0.91756488, -0.92811163, -1.58459522],
       [ 0.44650849, -1.75408489,  1.82755766, -0.41309323],
       [ 0.66343348, -1.15096015, -0.67111496, -0.81461321],
       [-0.04686698,  1.20385326,  1.67835257,  2.01095527]])

In [83]:
# 布尔条件组合（使用 & 和 |）
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [84]:
data[mask]

array([[-0.04618696, -0.01695548,  1.50295203, -0.55685797],
       [-1.44635553, -0.91756488, -0.92811163, -1.58459522],
       [ 0.84674012,  0.86007893,  0.73897786, -0.63438956],
       [ 0.44650849, -1.75408489,  1.82755766, -0.41309323]])

In [85]:
# 使用布尔索引设置值
data[data < 0] = 0
data

array([[0.        , 0.        , 1.50295203, 0.        ],
       [0.        , 0.25444505, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.84674012, 0.86007893, 0.73897786, 0.        ],
       [0.44650849, 0.        , 1.82755766, 0.        ],
       [0.66343348, 0.        , 0.        , 0.        ],
       [0.        , 1.20385326, 1.67835257, 2.01095527]])

In [86]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.25444505, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.66343348, 0.        , 0.        , 0.        ],
       [0.        , 1.20385326, 1.67835257, 2.01095527]])

### 1.8 花式索引

In [87]:
# 使用整数数组索引
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [88]:
# 以特定顺序选取行
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [89]:
# 使用负索引从末尾开始
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [90]:
# 传递多个索引数组
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [91]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [92]:
# 使用np.ix_函数组合索引
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 1.9 数组转置和轴对换

In [93]:
# 转置
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [94]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [95]:
# 计算矩阵内积
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

array([[ 4.77552325, -4.23809123, -0.61631007],
       [-4.23809123, 11.4833431 , -3.15643579],
       [-0.61631007, -3.15643579,  4.65087983]])

In [96]:
# 三维数组的transpose
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [97]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [98]:
# swapaxes交换两个轴
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [99]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 第2章：通用函数：快速的元素级数组函数

In [100]:
# 一元ufunc
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
# 平方根
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [102]:
# 指数
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [103]:
# 二元ufunc
x = np.random.randn(8)
y = np.random.randn(8)
x

array([-1.24099968, -1.54859791,  0.10174806,  0.09544751,  0.99907893,
       -0.44864992,  0.02247419,  0.593591  ])

In [104]:
y

array([ 0.64231915,  0.39204788,  0.77239607,  0.19591003, -0.10426779,
        1.0884307 , -0.60453675, -0.73025563])

In [105]:
# 最大值
np.maximum(x, y)

array([0.64231915, 0.39204788, 0.77239607, 0.19591003, 0.99907893,
       1.0884307 , 0.02247419, 0.593591  ])

In [106]:
# modf返回小数和整数部分
arr = np.random.randn(7) * 5
arr

array([-6.673738  ,  5.16282061,  8.16968193,  1.94806665,  3.62177544,
        4.68942588,  4.81468724])

In [107]:
remainder, whole_part = np.modf(arr)
remainder

array([-0.673738  ,  0.16282061,  0.16968193,  0.94806665,  0.62177544,
        0.68942588,  0.81468724])

In [108]:
whole_part

array([-6.,  5.,  8.,  1.,  3.,  4.,  4.])

## 第3章：利用数组进行数据处理

In [109]:
# np.where：三元表达式的矢量化
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

# 使用列表推导（慢！）
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

In [110]:
# 使用np.where（快！）
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [111]:
# np.where的典型用法：替换值
arr = np.random.randn(4, 4)
arr

array([[-1.59225745, -0.14808519,  0.76118078,  0.76408312],
       [-0.3089987 ,  0.53152176,  0.87819762,  0.90853545],
       [ 1.33162737,  1.99005449,  0.70935783,  0.97249769],
       [-1.50243201,  0.58676961,  0.59459681,  3.12259076]])

In [112]:
arr > 0

array([[False, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [113]:
np.where(arr > 0, 2, -2)

array([[-2, -2,  2,  2],
       [-2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [-2,  2,  2,  2]])

In [114]:
# 只替换正值
np.where(arr > 0, 2, arr)

array([[-1.59225745, -0.14808519,  2.        ,  2.        ],
       [-0.3089987 ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [-1.50243201,  2.        ,  2.        ,  2.        ]])

### 3.1 数学和统计方法

In [115]:
arr = np.random.randn(5, 4)
arr

array([[ 0.09306846,  0.38804209,  0.16891384, -1.2064495 ],
       [-0.41608969,  0.87831439, -0.50105195,  1.1312055 ],
       [-0.16436894,  0.618383  ,  0.39347205,  0.47099015],
       [-1.05618438,  0.20365237,  0.53042725,  2.31607797],
       [-0.08516098,  0.97524531,  0.19534194,  0.0701079 ]])

In [116]:
# 均值
arr.mean()

np.float64(0.2501968401693286)

In [117]:
np.mean(arr)

np.float64(0.2501968401693286)

In [118]:
# 求和
arr.sum()

np.float64(5.003936803386572)

In [119]:
# axis参数指定计算的轴
arr.mean(axis=1)

array([-0.13910628,  0.27309456,  0.32961907,  0.4984933 ,  0.28888354])

In [120]:
arr.sum(axis=0)

array([-1.62873553,  3.06363716,  0.78710314,  2.78193203])

In [121]:
# cumsum和cumprod：累计
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [122]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [123]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

### 3.2 用于布尔型数组的方法

In [124]:
arr = np.random.randn(100)
# 统计正值的数量
(arr > 0).sum()

np.int64(55)

In [125]:
# any和all
bools = np.array([False, False, True, False])
bools.any()

np.True_

In [126]:
bools.all()

np.False_

### 3.3 排序

In [127]:
arr = np.random.randn(6)
arr

array([ 1.57348356, -1.13361541, -1.11175954, -0.37082251,  0.13569801,
        0.6164239 ])

In [128]:
# 就地排序
arr.sort()
arr

array([-1.13361541, -1.11175954, -0.37082251,  0.13569801,  0.6164239 ,
        1.57348356])

In [129]:
# 多维数组按轴排序
arr = np.random.randn(5, 3)
arr

array([[ 1.21976839,  0.61282133,  0.3251014 ],
       [ 0.45170329, -0.13634963,  0.68150202],
       [ 1.04265198,  1.68534917,  1.98558117],
       [ 0.33212457,  0.13701588,  0.84002384],
       [ 0.78321368,  0.16249269,  0.96132296]])

In [130]:
arr.sort(1)
arr

array([[ 0.3251014 ,  0.61282133,  1.21976839],
       [-0.13634963,  0.45170329,  0.68150202],
       [ 1.04265198,  1.68534917,  1.98558117],
       [ 0.13701588,  0.33212457,  0.84002384],
       [ 0.16249269,  0.78321368,  0.96132296]])

In [131]:
# 计算分位数（例如中位数）
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))]

np.float64(-1.6839085180268363)

### 3.4 唯一化以及其他的集合逻辑

In [132]:
# np.unique：唯一值并排序
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [133]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [134]:
# np.in1d：测试成员资格
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

C:\Users\48769\AppData\Local\Temp\ipykernel_676\2382680740.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(values, [2, 3, 6])


array([ True, False, False,  True,  True, False,  True])

## 第4章：用于数组的文件输入输出

In [135]:
# np.save保存数组到磁盘
arr = np.arange(10)
np.save('some_array', arr)

In [136]:
# np.load加载数组
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
# np.savez保存多个数组
np.savez('array_archive.npz', a=arr, b=arr)
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
# np.savez_compressed压缩保存
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

## 第5章：线性代数

In [139]:
# 矩阵乘法
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [140]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [141]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [142]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [143]:
np.ones(3)

array([1., 1., 1.])

In [144]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [145]:
# numpy.linalg模块
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 0.19466495, -0.2644942 , -0.06115537, -0.32328796, -0.09108972],
       [-0.2644942 ,  1.16908317, -0.01165666,  1.21966399,  0.0164491 ],
       [-0.06115537, -0.01165666,  0.57044917, -0.20975931,  0.08009208],
       [-0.32328796,  1.21966399, -0.20975931,  1.57890247,  0.06414924],
       [-0.09108972,  0.0164491 ,  0.08009208,  0.06414924,  0.17058636]])

In [146]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.26865264e-16, -3.89971390e-17,
         4.11676476e-16,  1.08167461e-16],
       [ 2.11336201e-16,  1.00000000e+00,  9.15332603e-17,
        -6.99907239e-16,  5.10212597e-17],
       [-1.35157110e-16, -1.10175144e-16,  1.00000000e+00,
         4.60999814e-16,  1.25649589e-17],
       [-5.67892852e-17,  5.59967537e-16, -7.44549145e-17,
         1.00000000e+00, -4.44315950e-17],
       [-1.21076879e-17, -4.02861414e-16,  1.92502369e-18,
        -2.67022274e-16,  1.00000000e+00]])

In [147]:
q, r = qr(mat)
r

array([[-13.14876827,  -0.92945106,  -1.19717183,  -1.90583028,
         -7.87230269],
       [  0.        ,  -8.53158737,   3.84501798,   7.70089573,
         -5.39871125],
       [  0.        ,   0.        ,  -2.08690286,  -0.33547385,
          3.2289488 ],
       [  0.        ,   0.        ,   0.        ,  -0.52006617,
          1.56393692],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          4.5549942 ]])

## 第6章：伪随机数生成

In [148]:
# 标准正态分布
samples = np.random.normal(size=(4, 4))
samples

array([[ 0.46399793, -1.39287122, -0.71258968,  0.56141287],
       [ 0.05455983, -1.35517475,  1.6763794 , -0.04337987],
       [ 0.49996747,  0.97472417,  0.76592281, -0.64315891],
       [ 0.00454346,  0.7988478 ,  0.29197876, -1.22813821]])

In [149]:
# 设置随机种子
np.random.seed(1234)

In [150]:
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

## 补充：随机漫步示例

In [151]:
# 使用纯Python实现随机漫步
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)
len(walk)

1001

In [152]:
# 使用NumPy实现（更快！）
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()
walk.min()

np.int64(-9)

In [153]:
walk.max()

np.int64(60)

In [154]:
# 首次穿越时间：首次到达10或-10
(np.abs(walk) >= 10).argmax()

np.int64(297)

In [155]:
# 一次模拟多个随机漫步
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

array([[  1,   2,   3, ...,  46,  47,  46],
       [  1,   0,   1, ...,  40,  41,  42],
       [  1,   2,   3, ..., -26, -27, -28],
       ...,
       [  1,   0,   1, ...,  64,  65,  66],
       [  1,   2,   1, ...,   2,   1,   0],
       [ -1,  -2,  -3, ...,  32,  33,  34]], shape=(5000, 1000))

In [156]:
walks.max()

np.int64(122)

In [157]:
walks.min()

np.int64(-128)

In [158]:
# 计算首次穿越30的时间
hits30 = (np.abs(walks) >= 30).any(1)
hits30.sum()

np.int64(3368)

In [159]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

np.float64(509.99762470308787)