# NumPy 学习笔记

## 第1章：NumPy基础

### 1.1 NumPy ndarray：一种多维数组对象

In [1]:
# 导入numpy，约定俗成使用np作为别名
import numpy as np

In [2]:
# 生成随机数据
data = np.random.randn(2, 3)
data

array([[ 0.02419984, -0.69270309,  0.95791886],
       [ 1.59849009,  0.8188209 ,  0.04458543]])

In [3]:
# ndarray与标量运算
data * 10

array([[ 0.24199838, -6.92703094,  9.57918859],
       [15.98490092,  8.18820898,  0.44585426]])

In [4]:
data + data

array([[ 0.04839968, -1.38540619,  1.91583772],
       [ 3.19698018,  1.6376418 ,  0.08917085]])

In [5]:
# shape属性：各维度大小
data.shape

(2, 3)

In [6]:
# dtype属性：数组的数据类型
data.dtype

dtype('float64')

### 1.2 创建ndarray

In [7]:
# 使用array函数从列表创建数组
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
# 嵌套序列会创建多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# ndim属性：数组的维度数
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
# zeros创建全0数组
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# 创建多维zeros数组
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
# empty创建空数组（注意：值不一定是0！）
np.empty((2, 3, 2))

array([[[1.07284626e-317, 6.66323560e-317],
        [            nan, 1.24636384e-316],
        [            nan, 7.65483869e-317]],

       [[7.65483869e-317,             nan],
        [1.24636384e-316,             nan],
        [6.66323560e-317, 1.07284626e-317]]])

In [14]:
# arange是Python range的数组版
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 1.3 ndarray的数据类型

In [15]:
# 创建数组时指定dtype
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [16]:
arr2.dtype

dtype('int32')

In [17]:
# 使用astype转换数据类型
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [18]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [19]:
# 浮点数转整数会截断小数部分
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [20]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [21]:
# 字符串数字转数值
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

### 1.4 NumPy数组的运算

In [22]:
# 数组与数组的运算（逐元素）
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# 数组与标量运算（广播）
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [26]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [27]:
# 数组比较（返回布尔数组）
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [28]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### 1.5 基本的索引和切片

In [29]:
# 一维数组索引
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[5]

np.int64(5)

In [31]:
arr[5:8]

array([5, 6, 7])

In [32]:
# 注意：切片是视图，修改会影响原数组！
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [33]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [34]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [35]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [36]:
# 使用copy方法创建副本
arr_copy = arr[5:8].copy()
arr_copy

array([64, 64, 64])

In [37]:
# 二维数组索引
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [38]:
# 两种等价的索引方式
arr2d[0][2]

np.int64(3)

In [39]:
arr2d[0, 2]

np.int64(3)

In [40]:
# 三维数组索引
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
arr3d[1, 0]

array([7, 8, 9])

### 1.6 切片索引

In [45]:
# 一维数组切片
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [46]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [47]:
# 二维数组切片
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
# 二维数组双切片
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [50]:
arr2d[1, :2]

array([4, 5])

In [51]:
arr2d[:2, 2]

array([3, 6])

In [52]:
# 只写冒号表示选择整个轴
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [53]:
# 对切片赋值
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 1.7 布尔型索引

In [54]:
# 创建示例数据
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [55]:
data

array([[ 0.42657688, -1.91696938, -0.13782788,  0.81761113],
       [ 0.66323391,  1.21640593,  1.39522622,  0.44273257],
       [ 1.73571767, -0.51998319,  0.48052981, -0.28854455],
       [-0.44516381, -1.51495408, -1.03804955,  1.01975275],
       [-1.30664318,  0.03609045, -1.23732978, -0.24485299],
       [-0.42431092,  0.37339167, -1.65774544, -1.19615755],
       [-1.39627293,  0.10114298, -1.69930697,  0.33875285]])

In [56]:
# 布尔比较
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [57]:
# 使用布尔数组索引
data[names == 'Bob']

array([[ 0.42657688, -1.91696938, -0.13782788,  0.81761113],
       [-0.44516381, -1.51495408, -1.03804955,  1.01975275]])

In [58]:
# 布尔索引与切片结合
data[names == 'Bob', 2:]

array([[-0.13782788,  0.81761113],
       [-1.03804955,  1.01975275]])

In [59]:
data[names == 'Bob', 3]

array([0.81761113, 1.01975275])

In [60]:
# 使用 != 或 ~ 取反
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [61]:
data[~(names == 'Bob')]

array([[ 0.66323391,  1.21640593,  1.39522622,  0.44273257],
       [ 1.73571767, -0.51998319,  0.48052981, -0.28854455],
       [-1.30664318,  0.03609045, -1.23732978, -0.24485299],
       [-0.42431092,  0.37339167, -1.65774544, -1.19615755],
       [-1.39627293,  0.10114298, -1.69930697,  0.33875285]])

In [62]:
# 布尔条件组合（使用 & 和 |）
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [63]:
data[mask]

array([[ 0.42657688, -1.91696938, -0.13782788,  0.81761113],
       [ 1.73571767, -0.51998319,  0.48052981, -0.28854455],
       [-0.44516381, -1.51495408, -1.03804955,  1.01975275],
       [-1.30664318,  0.03609045, -1.23732978, -0.24485299]])

In [64]:
# 使用布尔索引设置值
data[data < 0] = 0
data

array([[0.42657688, 0.        , 0.        , 0.81761113],
       [0.66323391, 1.21640593, 1.39522622, 0.44273257],
       [1.73571767, 0.        , 0.48052981, 0.        ],
       [0.        , 0.        , 0.        , 1.01975275],
       [0.        , 0.03609045, 0.        , 0.        ],
       [0.        , 0.37339167, 0.        , 0.        ],
       [0.        , 0.10114298, 0.        , 0.33875285]])

In [65]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.66323391, 1.21640593, 1.39522622, 0.44273257],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.37339167, 0.        , 0.        ],
       [0.        , 0.10114298, 0.        , 0.33875285]])

### 1.8 花式索引

In [66]:
# 使用整数数组索引
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [67]:
# 以特定顺序选取行
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [68]:
# 使用负索引从末尾开始
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [69]:
# 传递多个索引数组
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [70]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [71]:
# 使用np.ix_函数组合索引
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 1.9 数组转置和轴对换

In [72]:
# 转置
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [74]:
# 计算矩阵内积
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

array([[ 4.91348386, -2.83575869,  0.08055148],
       [-2.83575869,  7.75882108, -1.22260901],
       [ 0.08055148, -1.22260901,  9.55969138]])

In [75]:
# 三维数组的transpose
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [76]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [77]:
# swapaxes交换两个轴
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [78]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 第2章：通用函数：快速的元素级数组函数

In [79]:
# 一元ufunc
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
# 平方根
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [81]:
# 指数
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [82]:
# 二元ufunc
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 1.00718738, -0.30151791, -1.81983331, -1.29087085,  0.0561582 ,
       -0.22189803,  0.76669951, -0.36686434])

In [83]:
y

array([-0.61354028, -0.48627539,  0.57618219, -0.56108919,  0.13619307,
        1.00630187, -0.77456774,  0.59382381])

In [84]:
# 最大值
np.maximum(x, y)

array([ 1.00718738, -0.30151791,  0.57618219, -0.56108919,  0.13619307,
        1.00630187,  0.76669951,  0.59382381])

In [85]:
# modf返回小数和整数部分
arr = np.random.randn(7) * 5
arr

array([  3.98497245,   2.42188385,   2.92169368,  -1.701993  ,
       -11.62062804,  -1.76179085,   3.75277194])

In [86]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.98497245,  0.42188385,  0.92169368, -0.701993  , -0.62062804,
       -0.76179085,  0.75277194])

In [87]:
whole_part

array([  3.,   2.,   2.,  -1., -11.,  -1.,   3.])

## 第3章：利用数组进行数据处理

In [88]:
# np.where：三元表达式的矢量化
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

# 使用列表推导（慢！）
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

In [89]:
# 使用np.where（快！）
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [90]:
# np.where的典型用法：替换值
arr = np.random.randn(4, 4)
arr

array([[ 0.898558  , -0.24030887, -0.0458768 , -0.3230605 ],
       [ 0.24990908, -0.20042408,  0.57438809, -0.39342481],
       [ 0.61799276, -0.54822165,  0.34812685, -0.31991449],
       [-0.1864216 ,  1.79504581, -0.98756376,  0.44074718]])

In [91]:
arr > 0

array([[ True, False, False, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [False,  True, False,  True]])

In [92]:
np.where(arr > 0, 2, -2)

array([[ 2, -2, -2, -2],
       [ 2, -2,  2, -2],
       [ 2, -2,  2, -2],
       [-2,  2, -2,  2]])

In [93]:
# 只替换正值
np.where(arr > 0, 2, arr)

array([[ 2.        , -0.24030887, -0.0458768 , -0.3230605 ],
       [ 2.        , -0.20042408,  2.        , -0.39342481],
       [ 2.        , -0.54822165,  2.        , -0.31991449],
       [-0.1864216 ,  2.        , -0.98756376,  2.        ]])

### 3.1 数学和统计方法

In [94]:
arr = np.random.randn(5, 4)
arr

array([[-0.91436457, -1.23480762,  0.71218946,  1.52866021],
       [-0.61152648,  0.41075143, -1.17252918,  0.73749671],
       [ 1.48545819,  0.34905242,  1.54038569, -0.27581048],
       [-0.24768513, -0.05531651, -0.09470061,  1.36310051],
       [-1.80443469, -1.31229589,  1.27857463,  1.22393434]])

In [95]:
# 均值
arr.mean()

np.float64(0.14530662183325918)

In [96]:
np.mean(arr)

np.float64(0.14530662183325918)

In [97]:
# 求和
arr.sum()

np.float64(2.9061324366651835)

In [98]:
# axis参数指定计算的轴
arr.mean(axis=1)

array([ 0.02291937, -0.15895188,  0.77477145,  0.24134957, -0.1535554 ])

In [99]:
arr.sum(axis=0)

array([-2.09255269, -1.84261616,  2.26392   ,  4.57738129])

In [100]:
# cumsum和cumprod：累计
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [102]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

### 3.2 用于布尔型数组的方法

In [103]:
arr = np.random.randn(100)
# 统计正值的数量
(arr > 0).sum()

np.int64(43)

In [104]:
# any和all
bools = np.array([False, False, True, False])
bools.any()

np.True_

In [105]:
bools.all()

np.False_

### 3.3 排序

In [106]:
arr = np.random.randn(6)
arr

array([ 0.23833666,  0.0154547 , -1.48826588, -1.94941146,  1.29606369,
       -0.7657464 ])

In [107]:
# 就地排序
arr.sort()
arr

array([-1.94941146, -1.48826588, -0.7657464 ,  0.0154547 ,  0.23833666,
        1.29606369])

In [108]:
# 多维数组按轴排序
arr = np.random.randn(5, 3)
arr

array([[ 1.58451492,  1.19690634,  0.33498212],
       [-1.11957586, -0.66420262, -0.66369167],
       [-0.05946669,  1.37888546, -0.87025289],
       [ 0.63725443, -0.20809867, -0.09351513],
       [ 1.35667229, -0.4569884 ,  0.42693496]])

In [109]:
arr.sort(1)
arr

array([[ 0.33498212,  1.19690634,  1.58451492],
       [-1.11957586, -0.66420262, -0.66369167],
       [-0.87025289, -0.05946669,  1.37888546],
       [-0.20809867, -0.09351513,  0.63725443],
       [-0.4569884 ,  0.42693496,  1.35667229]])

In [110]:
# 计算分位数（例如中位数）
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))]

np.float64(-1.6382678208725066)

### 3.4 唯一化以及其他的集合逻辑

In [111]:
# np.unique：唯一值并排序
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [112]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [113]:
# np.in1d：测试成员资格
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

C:\Users\48769\AppData\Local\Temp\ipykernel_10284\2382680740.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(values, [2, 3, 6])


array([ True, False, False,  True,  True, False,  True])

## 第4章：用于数组的文件输入输出

In [114]:
# np.save保存数组到磁盘
arr = np.arange(10)
np.save('some_array', arr)

In [115]:
# np.load加载数组
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
# np.savez保存多个数组
np.savez('array_archive.npz', a=arr, b=arr)
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
# np.savez_compressed压缩保存
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

## 第5章：线性代数

In [118]:
# 矩阵乘法
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [119]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [120]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [121]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [122]:
np.ones(3)

array([1., 1., 1.])

In [123]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [124]:
# numpy.linalg模块
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 38.02367826,  36.88222932, -48.77824494,  21.8456689 ,
         13.99162166],
       [ 36.88222932,  37.12545577, -47.56041072,  21.57314258,
         14.03493878],
       [-48.77824494, -47.56041072,  65.65379673, -28.19264121,
        -18.92741454],
       [ 21.8456689 ,  21.57314258, -28.19264121,  12.81913587,
          8.10220144],
       [ 13.99162166,  14.03493878, -18.92741454,   8.10220144,
          5.91056018]])

In [125]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  4.33947110e-15, -6.33757770e-15,
         7.66513637e-16, -6.26213671e-16],
       [ 3.69289895e-15,  1.00000000e+00, -4.17008160e-15,
        -1.12534892e-14,  1.70898715e-15],
       [ 5.10986533e-15, -3.45859741e-15,  1.00000000e+00,
         1.92541262e-15, -5.98421728e-17],
       [ 4.11440184e-15, -1.59025709e-14,  4.40867416e-14,
         1.00000000e+00, -4.49671933e-15],
       [-6.64743166e-15, -1.51966385e-14,  9.45773515e-15,
         8.74381082e-15,  1.00000000e+00]])

In [126]:
q, r = qr(mat)
r

array([[-2.27810693, -0.66646696, -0.21775543,  4.6886044 , -0.18292069],
       [ 0.        , -3.81793861,  1.5992366 ,  7.29315939,  4.26868817],
       [ 0.        ,  0.        , -0.65298218, -0.48002072, -1.51967129],
       [ 0.        ,  0.        ,  0.        , -0.75459668,  1.1464638 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.03426804]])

## 第6章：伪随机数生成

In [127]:
# 标准正态分布
samples = np.random.normal(size=(4, 4))
samples

array([[ 1.0965884 ,  1.36804569, -0.31415622, -0.97969484],
       [ 0.04132519, -0.34950638, -0.31214756, -0.26779577],
       [-0.32513258,  1.52778337, -1.11967384,  0.88852282],
       [-0.44307543, -0.55885892,  0.79043173, -0.76039274]])

In [128]:
# 设置随机种子
np.random.seed(1234)

In [129]:
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

## 补充：随机漫步示例

In [130]:
# 使用纯Python实现随机漫步
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)
len(walk)

1001

In [131]:
# 使用NumPy实现（更快！）
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()
walk.min()

np.int64(-9)

In [132]:
walk.max()

np.int64(60)

In [133]:
# 首次穿越时间：首次到达10或-10
(np.abs(walk) >= 10).argmax()

np.int64(297)

In [134]:
# 一次模拟多个随机漫步
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

array([[  1,   2,   3, ...,  46,  47,  46],
       [  1,   0,   1, ...,  40,  41,  42],
       [  1,   2,   3, ..., -26, -27, -28],
       ...,
       [  1,   0,   1, ...,  64,  65,  66],
       [  1,   2,   1, ...,   2,   1,   0],
       [ -1,  -2,  -3, ...,  32,  33,  34]], shape=(5000, 1000))

In [135]:
walks.max()

np.int64(122)

In [136]:
walks.min()

np.int64(-128)

In [137]:
# 计算首次穿越30的时间
hits30 = (np.abs(walks) >= 30).any(1)
hits30.sum()

np.int64(3368)

In [138]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

np.float64(509.99762470308787)