# NumPy 学习笔记

## 第1章：NumPy基础

### 1.1 NumPy ndarray：一种多维数组对象

In [2]:
# 导入numpy，约定俗成使用np作为别名
import numpy as np

In [3]:
# 生成随机数据
data = np.random.randn(2, 3)
data

array([[ 1.59626733, -0.37101781, -0.15282585],
       [-1.10613669, -0.18525978, -0.61502667]])

In [4]:
# ndarray与标量运算
data * 10

array([[ 15.96267334,  -3.71017812,  -1.5282585 ],
       [-11.06136694,  -1.85259784,  -6.15026673]])

In [5]:
data + data

array([[ 3.19253467, -0.74203562, -0.3056517 ],
       [-2.21227339, -0.37051957, -1.23005335]])

In [6]:
# shape属性：各维度大小
data.shape

(2, 3)

In [7]:
# dtype属性：数组的数据类型
data.dtype

dtype('float64')

### 1.2 创建ndarray

In [8]:
# 使用array函数从列表创建数组
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
# 嵌套序列会创建多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
# ndim属性：数组的维度数
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [12]:
# zeros创建全0数组
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# 创建多维zeros数组
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
# empty创建空数组（注意：值不一定是0！）
np.empty((2, 3, 2))

array([[[1.07284626e-317, 6.66323560e-317],
        [            nan, 1.24636384e-316],
        [            nan, 7.65483869e-317]],

       [[7.65483869e-317,             nan],
        [1.24636384e-316,             nan],
        [6.66323560e-317, 1.07284626e-317]]])

In [15]:
# arange是Python range的数组版
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 1.3 ndarray的数据类型

In [16]:
# 创建数组时指定dtype
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int32')

In [18]:
# 使用astype转换数据类型
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [19]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [20]:
# 浮点数转整数会截断小数部分
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [21]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [22]:
# 字符串数字转数值
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

### 1.4 NumPy数组的运算

In [23]:
# 数组与数组的运算（逐元素）
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [24]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [25]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# 数组与标量运算（广播）
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [27]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [28]:
# 数组比较（返回布尔数组）
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [29]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### 1.5 基本的索引和切片

In [30]:
# 一维数组索引
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[5]

np.int64(5)

In [32]:
arr[5:8]

array([5, 6, 7])

In [33]:
# 注意：切片是视图，修改会影响原数组！
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [34]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [35]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [36]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [37]:
# 使用copy方法创建副本
arr_copy = arr[5:8].copy()
arr_copy

array([64, 64, 64])

In [38]:
# 二维数组索引
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [39]:
# 两种等价的索引方式
arr2d[0][2]

np.int64(3)

In [40]:
arr2d[0, 2]

np.int64(3)

In [41]:
# 三维数组索引
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr3d[1, 0]

array([7, 8, 9])

### 1.6 切片索引

In [46]:
# 一维数组切片
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [47]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [48]:
# 二维数组切片
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
# 二维数组双切片
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [51]:
arr2d[1, :2]

array([4, 5])

In [52]:
arr2d[:2, 2]

array([3, 6])

In [53]:
# 只写冒号表示选择整个轴
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [54]:
# 对切片赋值
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 1.7 布尔型索引

In [55]:
# 创建示例数据
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [56]:
data

array([[ 0.93401307,  0.78334974,  1.39382507,  2.10701015],
       [-0.06356556,  0.20549388, -0.18114605,  1.42228203],
       [ 1.21742049, -2.3856339 ,  0.9805116 , -0.94383199],
       [-0.14814182,  0.56150225,  0.72403868, -0.1115102 ],
       [-0.55152975,  1.23828131,  1.96967782,  1.70210783],
       [-0.69293204,  0.04324274, -1.66178353,  1.02216384],
       [-1.00657248,  1.37384272,  0.06134551, -0.07652026]])

In [57]:
# 布尔比较
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [58]:
# 使用布尔数组索引
data[names == 'Bob']

array([[ 0.93401307,  0.78334974,  1.39382507,  2.10701015],
       [-0.14814182,  0.56150225,  0.72403868, -0.1115102 ]])

In [59]:
# 布尔索引与切片结合
data[names == 'Bob', 2:]

array([[ 1.39382507,  2.10701015],
       [ 0.72403868, -0.1115102 ]])

In [60]:
data[names == 'Bob', 3]

array([ 2.10701015, -0.1115102 ])

In [61]:
# 使用 != 或 ~ 取反
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [62]:
data[~(names == 'Bob')]

array([[-0.06356556,  0.20549388, -0.18114605,  1.42228203],
       [ 1.21742049, -2.3856339 ,  0.9805116 , -0.94383199],
       [-0.55152975,  1.23828131,  1.96967782,  1.70210783],
       [-0.69293204,  0.04324274, -1.66178353,  1.02216384],
       [-1.00657248,  1.37384272,  0.06134551, -0.07652026]])

In [63]:
# 布尔条件组合（使用 & 和 |）
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [64]:
data[mask]

array([[ 0.93401307,  0.78334974,  1.39382507,  2.10701015],
       [ 1.21742049, -2.3856339 ,  0.9805116 , -0.94383199],
       [-0.14814182,  0.56150225,  0.72403868, -0.1115102 ],
       [-0.55152975,  1.23828131,  1.96967782,  1.70210783]])

In [65]:
# 使用布尔索引设置值
data[data < 0] = 0
data

array([[0.93401307, 0.78334974, 1.39382507, 2.10701015],
       [0.        , 0.20549388, 0.        , 1.42228203],
       [1.21742049, 0.        , 0.9805116 , 0.        ],
       [0.        , 0.56150225, 0.72403868, 0.        ],
       [0.        , 1.23828131, 1.96967782, 1.70210783],
       [0.        , 0.04324274, 0.        , 1.02216384],
       [0.        , 1.37384272, 0.06134551, 0.        ]])

In [66]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.20549388, 0.        , 1.42228203],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.04324274, 0.        , 1.02216384],
       [0.        , 1.37384272, 0.06134551, 0.        ]])

### 1.8 花式索引

In [67]:
# 使用整数数组索引
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [68]:
# 以特定顺序选取行
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [69]:
# 使用负索引从末尾开始
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [70]:
# 传递多个索引数组
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [71]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [72]:
# 使用np.ix_函数组合索引
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 1.9 数组转置和轴对换

In [73]:
# 转置
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [74]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [75]:
# 计算矩阵内积
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

array([[ 4.05597619, -1.40793192, -0.32558157],
       [-1.40793192,  6.09363378,  1.2864436 ],
       [-0.32558157,  1.2864436 ,  3.09746552]])

In [76]:
# 三维数组的transpose
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [77]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [78]:
# swapaxes交换两个轴
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [79]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 第2章：通用函数：快速的元素级数组函数

In [80]:
# 一元ufunc
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
# 平方根
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [82]:
# 指数
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [83]:
# 二元ufunc
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 1.55408745,  0.57526485, -0.29311062, -0.72021148,  1.22332595,
        0.04768034,  1.33178808, -0.54862725])

In [84]:
y

array([ 0.46071444, -0.41424738, -0.12357719,  0.01216719,  0.7976188 ,
        0.84237146,  0.64445909,  0.72459532])

In [85]:
# 最大值
np.maximum(x, y)

array([ 1.55408745,  0.57526485, -0.12357719,  0.01216719,  1.22332595,
        0.84237146,  1.33178808,  0.72459532])

In [86]:
# modf返回小数和整数部分
arr = np.random.randn(7) * 5
arr

array([ 6.58880382, -0.15342575, -1.44518606,  5.65239719,  2.5506917 ,
        5.35547275, -5.61115789])

In [87]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.58880382, -0.15342575, -0.44518606,  0.65239719,  0.5506917 ,
        0.35547275, -0.61115789])

In [88]:
whole_part

array([ 6., -0., -1.,  5.,  2.,  5., -5.])

## 第3章：利用数组进行数据处理

In [89]:
# np.where：三元表达式的矢量化
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

# 使用列表推导（慢！）
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

In [90]:
# 使用np.where（快！）
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [91]:
# np.where的典型用法：替换值
arr = np.random.randn(4, 4)
arr

array([[-0.65463383, -0.23326813, -1.6860324 , -1.14784974],
       [ 0.88433268,  0.69290668,  0.63790538, -0.55786919],
       [ 0.71864644, -0.24742592, -1.74668357,  0.43404212],
       [-0.22287908,  0.01650434, -0.68638951,  1.66117438]])

In [92]:
arr > 0

array([[False, False, False, False],
       [ True,  True,  True, False],
       [ True, False, False,  True],
       [False,  True, False,  True]])

In [93]:
np.where(arr > 0, 2, -2)

array([[-2, -2, -2, -2],
       [ 2,  2,  2, -2],
       [ 2, -2, -2,  2],
       [-2,  2, -2,  2]])

In [94]:
# 只替换正值
np.where(arr > 0, 2, arr)

array([[-0.65463383, -0.23326813, -1.6860324 , -1.14784974],
       [ 2.        ,  2.        ,  2.        , -0.55786919],
       [ 2.        , -0.24742592, -1.74668357,  2.        ],
       [-0.22287908,  2.        , -0.68638951,  2.        ]])

### 3.1 数学和统计方法

In [95]:
arr = np.random.randn(5, 4)
arr

array([[-0.02438414,  1.53623979,  0.92950389,  0.95281383],
       [ 0.90032177,  0.52402691,  0.57166048, -2.22301849],
       [ 2.06495136,  1.24519675,  0.51744374,  1.00330393],
       [ 0.25016699, -0.86875218, -1.77125911, -0.29203223],
       [ 1.60817045, -0.14579456, -0.19279195, -0.45470629]])

In [96]:
# 均值
arr.mean()

np.float64(0.30655304719197024)

In [97]:
np.mean(arr)

np.float64(0.30655304719197024)

In [98]:
# 求和
arr.sum()

np.float64(6.131060943839405)

In [99]:
# axis参数指定计算的轴
arr.mean(axis=1)

array([ 0.84854334, -0.05675233,  1.20772395, -0.67046913,  0.20371941])

In [100]:
arr.sum(axis=0)

array([ 4.79922644,  2.29091671,  0.05455705, -1.01363926])

In [101]:
# cumsum和cumprod：累计
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [103]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

### 3.2 用于布尔型数组的方法

In [104]:
arr = np.random.randn(100)
# 统计正值的数量
(arr > 0).sum()

np.int64(58)

In [105]:
# any和all
bools = np.array([False, False, True, False])
bools.any()

np.True_

In [106]:
bools.all()

np.False_

### 3.3 排序

In [107]:
arr = np.random.randn(6)
arr

array([ 0.28392418,  1.28712479,  0.19738709,  0.82471379, -0.09973118,
        0.72744111])

In [108]:
# 就地排序
arr.sort()
arr

array([-0.09973118,  0.19738709,  0.28392418,  0.72744111,  0.82471379,
        1.28712479])

In [109]:
# 多维数组按轴排序
arr = np.random.randn(5, 3)
arr

array([[-0.3771823 ,  0.59918932,  0.60391278],
       [ 0.35141677,  1.4056087 ,  0.48089388],
       [ 0.16042299, -0.49061738, -1.10030039],
       [ 1.71641907,  0.77805588, -1.47025674],
       [-0.53746814, -0.07967474, -1.10345161]])

In [110]:
arr.sort(1)
arr

array([[-0.3771823 ,  0.59918932,  0.60391278],
       [ 0.35141677,  0.48089388,  1.4056087 ],
       [-1.10030039, -0.49061738,  0.16042299],
       [-1.47025674,  0.77805588,  1.71641907],
       [-1.10345161, -0.53746814, -0.07967474]])

In [111]:
# 计算分位数（例如中位数）
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))]

np.float64(-1.7352668378507439)

### 3.4 唯一化以及其他的集合逻辑

In [112]:
# np.unique：唯一值并排序
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [113]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [114]:
# np.in1d：测试成员资格
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

C:\Users\48769\AppData\Local\Temp\ipykernel_3012\2382680740.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(values, [2, 3, 6])


array([ True, False, False,  True,  True, False,  True])

## 第4章：用于数组的文件输入输出

In [115]:
# np.save保存数组到磁盘
arr = np.arange(10)
np.save('some_array', arr)

In [116]:
# np.load加载数组
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
# np.savez保存多个数组
np.savez('array_archive.npz', a=arr, b=arr)
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
# np.savez_compressed压缩保存
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

## 第5章：线性代数

In [119]:
# 矩阵乘法
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [120]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [121]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [122]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [123]:
np.ones(3)

array([1., 1., 1.])

In [124]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [125]:
# numpy.linalg模块
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 416.5588762 , -322.80771543,  -80.32547918, -474.20115364,
        -326.04013407],
       [-322.80771543,  250.37059258,   62.19136698,  367.58512309,
         252.76616725],
       [ -80.32547918,   62.19136698,   15.72524274,   91.29204427,
          62.72651439],
       [-474.20115364,  367.58512309,   91.29204427,  540.3005432 ,
         371.42266705],
       [-326.04013407,  252.76616725,   62.72651439,  371.42266705,
         255.49701137]])

In [126]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  5.72570539e-13, -5.76837761e-14,
        -1.66695095e-13, -5.45650480e-15],
       [-3.94372321e-13,  1.00000000e+00,  4.38529271e-14,
         3.21224028e-13,  1.92600610e-13],
       [-1.58752130e-13, -1.17382989e-13,  1.00000000e+00,
         1.66416356e-14,  7.30223771e-14],
       [-2.79155059e-13,  5.90597288e-14, -1.24353096e-14,
         1.00000000e+00,  1.68153193e-13],
       [ 3.59472791e-14,  4.11628144e-14, -5.69393275e-14,
        -3.09841769e-13,  1.00000000e+00]])

In [127]:
q, r = qr(mat)
r

array([[-8.33862675e+00, -3.72245239e+00, -6.20504359e+00,
        -2.01998570e+00, -2.49913927e+00],
       [ 0.00000000e+00, -5.32636443e+00,  2.72321642e+00,
         1.03623816e-01,  4.45188839e+00],
       [ 0.00000000e+00,  0.00000000e+00, -3.16646294e+00,
         2.26460425e+00, -2.51464652e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -4.68380313e+00,  6.81201747e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.62787656e-03]])

## 第6章：伪随机数生成

In [128]:
# 标准正态分布
samples = np.random.normal(size=(4, 4))
samples

array([[ 1.11310907, -0.65414058,  0.53827926,  1.24662288],
       [-0.58241803, -0.15660904,  0.51031988,  0.30141223],
       [-0.52435377,  0.2531571 ,  0.12965115, -1.47918794],
       [-0.27759426,  0.38991672, -0.65864838,  0.67947845]])

In [129]:
# 设置随机种子
np.random.seed(1234)

In [130]:
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

## 补充：随机漫步示例

In [131]:
# 使用纯Python实现随机漫步
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)
len(walk)

1001

In [132]:
# 使用NumPy实现（更快！）
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()
walk.min()

np.int64(-9)

In [133]:
walk.max()

np.int64(60)

In [134]:
# 首次穿越时间：首次到达10或-10
(np.abs(walk) >= 10).argmax()

np.int64(297)

In [135]:
# 一次模拟多个随机漫步
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

array([[  1,   2,   3, ...,  46,  47,  46],
       [  1,   0,   1, ...,  40,  41,  42],
       [  1,   2,   3, ..., -26, -27, -28],
       ...,
       [  1,   0,   1, ...,  64,  65,  66],
       [  1,   2,   1, ...,   2,   1,   0],
       [ -1,  -2,  -3, ...,  32,  33,  34]], shape=(5000, 1000))

In [136]:
walks.max()

np.int64(122)

In [137]:
walks.min()

np.int64(-128)

In [138]:
# 计算首次穿越30的时间
hits30 = (np.abs(walks) >= 30).any(1)
hits30.sum()

np.int64(3368)

In [139]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

np.float64(509.99762470308787)