In [ ]:
data = np.random.randn(2, 3)
data
data * 10

array([[  2.90870565,  -1.14432178, -15.31477693],
       [ -4.35777088,   8.40183185,   3.09115381]])

In [3]:
data.shape

(2, 3)

In [4]:
data.dtype

dtype('float64')

In [5]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
data2=[[1,2,3],[4,5,6]]
arr2=np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])