# 一、ndarry数组
## 1.1 ndarry的特性
### 1.1.1 多维性

In [5]:
import numpy as np

In [6]:
arr = np.array(5)#创建一个0维数组
print(arr)
print(arr.ndim) # 0维数组的维度是0

5
0


In [7]:
arr = np.array([1,2,3,4,5])#创建一个1维数组
print(arr)
print("arr的维度是:",arr.ndim) # 1维数组的维度是1


[1 2 3 4 5]
arr的维度是: 1


In [8]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])#创建一个2维数组
print(arr)
print("arr的维度是:",arr.ndim) # 2维数组的维度是2


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
arr的维度是: 2


### 同质性